package io.github.fengyanglin09.springbootlab.lessons.lesson08_error_handling.model;

/**
 * Success response returned when inventory is reserved.
 */
public record Lesson08OrderReservationResponse(
        /*
         * The reservation id is generated by the service so tests can prove the
         * request passed validation and reached the application logic.
         */
        String reservationId,
        String sku,
        int quantity,
        String customerId,
        String status,
        String message
) {
}
