package io.github.fengyanglin09.droolssandbox.drools.droolsConfig;

unit DiscountRuleUnit;

import io.github.fengyanglin09.droolssandbox.drools.models.RulePhase;


rule "Missing customer type"
@category(validation)
salience 100
activation-group "validation"
when
    $context : /contexts[ phase == RulePhase.VALIDATION ]
    $config : /configs
    $request : /requests[ customerType == null ]
    $result : /results[ valid == true ]
then

    $result.getFiredRules().add("Missing customer type");

    modify($result){
        setValid(false),
        setDiscountPercent(0),
        setReason("Customer type is required")
    }
end

rule "Missing discount mode"
@category(validation)
salience 90
activation-group "validation"
when
    $context : /contexts[ phase == RulePhase.VALIDATION ]
    $request : /requests[ discountMode == null ]
    $result : /results[ valid == true ]
then

    $result.getFiredRules().add("Missing discount mode");

    modify($result) {
        setValid(false),
        setDiscountPercent(0),
        setReason("Discount mode is required")
    }
end

rule "Missing order amount"
@category(validation)
salience 80
activation-group "validation"
when
    $context : /contexts[ phase == RulePhase.VALIDATION ]
    $request : /requests[ orderAmount == null ]
    $result : /results[ valid == true ]
then

    $result.getFiredRules().add("Missing order amount");

    modify($result) {
        setValid(false),
        setDiscountPercent(0),
        setReason("Order amount is required")
    }
end
