package io.github.fengyanglin09.droolssandbox.drools.droolsConfig;
unit DiscountRuleUnit;

import io.github.fengyanglin09.droolssandbox.drools.models.CustomerType;
import io.github.fengyanglin09.droolssandbox.drools.models.DiscountMode;
import io.github.fengyanglin09.droolssandbox.drools.models.RulePhase;

rule "Large order discount"
@category(discount)
salience 30
activation-group "discount"
when
    $context : /contexts[ phase == RulePhase.DISCOUNT ]
    $config : /configs
    $request : /requests[
        discountMode in (DiscountMode.AUTO, DiscountMode.LARGE_ORDER_ONLY),
        orderAmount != null,
        orderAmount.compareTo($config.getLargeOrderMinimumAmount()) > 0
    ]
    $result : /results[ valid == true, reason == null ]
then
//    $result.getFiredRules().add("Large order discount");

    modify($result) {
        setDiscountPercent($config.getLargeOrderPercent()),
        setReason("Large order over 500")
    }
end

rule "VIP discount"
@category(discount)
salience 20
activation-group "discount"
when
    $context : /contexts[ phase == RulePhase.DISCOUNT ]
    $config : /configs
    $request : /requests[
        discountMode in (DiscountMode.AUTO, DiscountMode.VIP_ONLY),
        customerType == CustomerType.VIP,
        orderAmount != null,
        orderAmount.compareTo($config.getVipMinimumAmount()) > 0
    ]
    $result : /results[ valid == true, reason == null ]
then
//    $result.getFiredRules().add("VIP discount");

    modify($result) {
        setDiscountPercent($config.getVipPercent()),
        setReason("VIP customer with order over 100")
    }
end

rule "Normal discount"
@category(discount)
salience 10
activation-group "discount"
when
    $context : /contexts[ phase == RulePhase.DISCOUNT ]
    $config : /configs
    $request : /requests[
        discountMode in (DiscountMode.AUTO, DiscountMode.NORMAL_ONLY),
        customerType == CustomerType.NORMAL,
        orderAmount != null,
        orderAmount.compareTo($config.getNormalMinimumAmount()) > 0
    ]
    $result : /results[ valid == true, reason == null ]
then
//    $result.getFiredRules().add("Normal discount");

    modify($result) {
        setDiscountPercent($config.getNormalPercent()),
        setReason("Normal customer with order over 200")
    }
end

rule "No discount matched"
@category(discount)
salience -100
when
    $context : /contexts[ phase == RulePhase.DISCOUNT ]
    $result : /results[
        valid == true,
        discountPercent == 0,
        reason == null
    ]
then
//    $result.getFiredRules().add("No discount matched");

    modify($result) {
        setReason("No discount rule matched")
    }
end
